apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER
           env:
             - name: FRONT_SIGNIN_ERROR_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: FRONT_SIGNIN_ERROR_URL
             - name: FRONT_PROFILE_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: FRONT_PROFILE_URL
             - name: INCLUDE_TESTING_MODULE
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: INCLUDE_TESTING_MODULE
             - name: JWT_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: JWT_SECRET_KEY
             - name: JWT_EXPIRES_IN
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: JWT_EXPIRES_IN
             - name: DB_LOGGING
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: DB_LOGGING
             - name: RECOVERY_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: RECOVERY_URL
             - name: REGISTRATION_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: REGISTRATION_URL
             - name: PASSWORD_RECOVERY_CODE_LIFETIME_SECS
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: PASSWORD_RECOVERY_CODE_LIFETIME_SECS
             - name: MAIL_MODULE_HOST
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: MAIL_MODULE_HOST
             - name: MAIL_MODULE_USER
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: MAIL_MODULE_USER
             - name: MAIL_MODULE_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: MAIL_MODULE_PASSWORD
             - name: MAIL_MODULE_FROM
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: MAIL_MODULE_FROM
             - name: RECAPTCHA_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: RECAPTCHA_SECRET_KEY
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: GITHUB_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: GITHUB_CALLBACK_URL
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: GOOGLE_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: GOOGLE_CALLBACK_URL
             - name: URL_TOKEN_SUCCESS
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: URL_TOKEN_SUCCESS
             - name: MONGO_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: MONGO_URL
             - name: BUCKET_NAME
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: BUCKET_NAME
             - name: BUCKET_SECRET_ACCESS_KEY
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: BUCKET_SECRET_ACCESS_KEY
             - name: BUCKET_ACCESS_KEY_ID
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: BUCKET_ACCESS_KEY_ID
             - name: BUCKET_ENDPOINT
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: BUCKET_ENDPOINT
             - name: BUCKET_REGION
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: BUCKET_REGION
             - name: FILES_API_HOST
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: FILES_API_HOST
             - name: FILES_API_PORT
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: FILES_API_PORT
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: DATABASE_URL
             - name: SHADOW_DB_URL
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: SHADOW_DB_URL
             - name: EMAIL_CONFIRMATION_CODE_LIFETIME_SECS
               valueFrom:
                 secretKeyRef:
                   name: mypixelgram-main-api-production-config-secret
                   key: EMAIL_CONFIRMATION_CODE_LIFETIME_SECS
